version: "3.7"
services:
  node-app:
    build: ./gate-simulator
    image: node-app-1
    ports:
      - "9999:9999"
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
  mysql:
    image: mysql:8.0.18
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass